# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/v4/*"
  to = "https://api.igdb.com/v4/"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = '*'
      Access-Control-Allow-Headers = 'Content-Type'
      Access-Control-Allow-Methods = 'GET, POST, OPTIONS'