/** @format */

export const SEARCH = 'SEARCH';
export const GET_GAMES_BEGIN = 'GET_GAMES_BEGIN';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';
export const GET_SINGLE_GAME_BEGIN = 'GET_SINGLE_GAME_BEGIN';
export const GET_SINGLE_GAME_SUCCESS = 'GET_SINGLE_GAME_SUCCESS';
export const GET_SINGLE_GAME_ERROR = 'GET_SINGLE_GAME_ERROR';

export const CHANGE_PAGE = 'CHANGE_PAGE';
