/** @format */

export const GET_GAMES_BEGIN = 'GET_GAMES_BEGIN';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

export const GET_SINGLE_GAME_BEGIN = 'GET_SINGLE_GAME_BEGIN';
export const GET_SINGLE_GAME_SUCCESS = 'GET_SINGLE_GAME_SUCCESS';
export const GET_SINGLE_GAME_ERROR = 'GET_SINGLE_GAME_ERROR';

export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_HANDLER = 'SEARCH_HANDLER';

export const SEARCH_MODAL_HANDLER = 'SEARCH_MODAL_HANDLER';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
